### ISSUE TITLE
Addon does not work with the latest version of Docker Image File

### ISSUE THREAD

**Issue by Frostoman** [clarkemw/moonlight-embedded-launcher#21]
Hello. I can't get the addon to work on a freshly installed Libreelec 9.2.8. The installation and pairing are successful, but when I try to connect to the computer, I only see a black screen.

If I restore Libreelec from a backup, everything works fine.

**Comment by Frostoman** [comment]
Some additional information. I did a moonlight docker image update on a Libreelec restored from backup and got the same black screen. Looks like that something is wrong with that image...
![photo_2023-09-27_16-33-59](https://github.com/clarkemw/script.moonlight-embedded-launcher/assets/32976590/5fac3c76-4e80-4c42-8b30-a56d54fd100d)

**Comment by clarkemw** [comment]
Sorry about that I tried to update the docker image to a newer version of Raspbian because it had an error when it tried to build moonlight-embedded 2.6.0.  I reverted the container back to Raspbian Bullseye and it seems to be working on my end.  You can refresh the docker image by going to `Configure/Docker Update` in the Kodi addon.  Please let me know if it works for you.

**Comment by Frostoman** [comment]
Tried fresh install - works fine. Updating existing installation - the same. Thanks!
